### ISSUE TITLE
JS error when scrolling outside <html>

### ISSUE THREAD

**Issue by wolthers** [lazd/iNoBounce#40] opened 2017-08-30 07:11 UTC
If body and html don't have at least height 100% which is sometimes the case in apps that don't set `html { height: 100% } body { min-height: 100% }`, el.parentNode will be `document` and `window.getComputedStyle(document)` will throw an error. To fix this, I suggest changing line 16 from:

    while (el !== document.body) {

to 

    while (el !== document.body && el !== document) {

**Comment by lazd** [comment] 2017-08-30 16:30
Very odd. Are you saying the tree will change based on whether `height` is set in CSS? That's a side effect I never imagined... Can you produce something that reproduces this so I can test it?

Thanks!

**Comment by wolthers** [comment] 2017-08-31 08:30
Here: https://codepen.io/wolthers/pen/OjrQgJ

**Comment by wolthers** [comment] 2017-09-20 14:01
Any update on this?

**Comment by lazd** [comment] 2017-09-20 14:59
I can't reproduce it with the provided pen. What error is supposed to be thrown?

**Comment by wolthers** [comment] 2017-09-20 15:17
You need to emulate touch for it to work. When body is not 100% height, it throws an error:

![image](https://user-images.githubusercontent.com/841834/30651987-768d74e2-9e27-11e7-8847-82b8fed47974.png)
![image](https://user-images.githubusercontent.com/841834/30652017-8d87fa50-9e27-11e7-9d39-e91a01c26b2d.png)

**Comment by lazd** [comment] 2017-09-20 15:27
Got it! Can you please send a PR for your suggested change? I'll get it merged.

**Comment by wolthers** [comment] 2017-09-20 16:02
Done https://github.com/lazd/iNoBounce/pull/41

**Closed** 2017-09-20 16:19 UTC
